name: databinder
description: Data binding via object mirrors.
version: 0.2.0
author: Victor Savkin <vic.savkin@gmail.com>
homepage: http://github.com/vsavkin/databinder
dependencies:
  unittest: any
  browser: any